kubevault/prometheus-exporter

- docs/reference/csi-driver/_index.md
- docs/reference/csi-driver/csi-vault.md
- docs/reference/csi-driver/csi-vault_init.md
- docs/reference/csi-driver/csi-vault_version.md
- docs/reference/operator/_index.md
- docs/reference/operator/vault-operator.md
- docs/reference/operator/vault-operator_run.md
- docs/reference/operator/vault-operator_version.md
> Add cli reference docs

- docs/reference/cli/_index.md
- docs/reference/cli/vault.md
- docs/reference/cli/vault_approve.md
- docs/reference/cli/vault_deny.md
- docs/reference/cli/vault_version.md
- docs/setup/cli/install.md
> Add docs for cli

- docs/reference/cli/vault.md
- docs/reference/cli/vault_approve.md
- docs/reference/cli/vault_deny.md
- docs/reference/cli/vault_version.md
- docs/reference/csi-driver/csi-vault.md
- docs/reference/csi-driver/csi-vault_run.md
- docs/reference/csi-driver/csi-vault_version.md
- docs/reference/operator/vault-operator.md
- docs/reference/operator/vault-operator_run.md
- docs/reference/operator/vault-operator_version.md
> Update cli references

- .spelling
- docs/concepts/database-crds/databaseaccessrequest.md
- docs/concepts/policy-crds/vaultpolicybinding.md
- docs/concepts/secret-engine-crds/awsaccesskeyrequest.md
- docs/concepts/vault-server-crds/auth-methods/appbinding.md
- docs/concepts/vault-server-crds/auth-methods/kubernetes.md
- docs/concepts/vault-server-crds/storage/inmem.md
- docs/concepts/vault-server-crds/unsealer/kubernetes_secret.md
- docs/concepts/vault-server-crds/vaultserver.md
- docs/examples/monitoring/csi-driver/prom-builtin-conf.yaml
- docs/examples/monitoring/vault-operator/prom-server-conf.yaml
- docs/guides/monitoring/csi-driver/builtin.md
- docs/guides/monitoring/vault-operator/builtin.md
- docs/guides/platforms/external-vault.md
- docs/guides/policy-management/overview.md
- docs/guides/secret-engines/aws/csi-driver.md
- docs/guides/secret-engines/aws/overview.md
- docs/guides/secret-engines/kv/csi-driver.md
- docs/guides/secret-engines/mongodb/csi-driver.md
- docs/guides/secret-engines/mongodb/overview.md
- docs/guides/secret-engines/mysql/csi-driver.md
- docs/guides/secret-engines/mysql/overview.md
- docs/guides/secret-engines/pki/csi-driver.md
- docs/guides/secret-engines/postgres/csi-driver.md
- docs/guides/secret-engines/postgres/overview.md
> Various fixes

- docs/examples/csi-driver/aws/csi-aws-storageclass.yaml
- docs/examples/csi-driver/database/mongodb/csi-storageclass.yaml
- docs/examples/csi-driver/database/mysql/csi-storageclass.yaml
- docs/examples/csi-driver/database/postgres/csi-storageclass.yaml
- docs/examples/csi-driver/kv/csi-storageclass.yaml
- docs/examples/csi-driver/pki/storageclass.yaml
- docs/guides/secret-engines/aws/csi-driver.md
- docs/guides/secret-engines/kv/csi-driver.md
- docs/guides/secret-engines/mongodb/csi-driver.md
- docs/guides/secret-engines/mysql/csi-driver.md
- docs/guides/secret-engines/pki/csi-driver.md
- docs/guides/secret-engines/postgres/csi-driver.md
- docs/setup/csi-driver/install.md
- docs/setup/csi-driver/overview.md
- docs/setup/csi-driver/uninstall.md
> Remove reference to 0.2.0 from 0.1.0 release

- docs/guides/secret-engines/aws/csi-driver.md
- docs/guides/secret-engines/kv/csi-driver.md
- docs/guides/secret-engines/mongodb/csi-driver.md
- docs/guides/secret-engines/mysql/csi-driver.md
- docs/guides/secret-engines/pki/csi-driver.md
- docs/guides/secret-engines/postgres/csi-driver.md
> Use details/summary to show Vault config for csi driver

- docs/concepts/vault-server-crds/unsealer/aws_kms_ssm.md
- docs/examples/guides/provider/eks/my-vault.yaml
- docs/guides/platforms/eks.md
this PR add documentation for the new option added in https://github.com/kubevault/operator/pull/203
> Document ssmKeyPrefix option in VaultServer

- .github/workflows/ci.yml
> Check for broken links

- docs/setup/csi-driver/install.md
- docs/setup/operator/install.md
> Add Helm 3 instructions

- docs/concepts/vault-server-crds/storage/postgresql.md
- docs/concepts/vault-server-crds/storage/swift.md
- docs/concepts/vault-server-crds/unsealer/azure_key_vault.md
- docs/examples/guides/provider/aks/my-vault.yaml
- docs/guides/platforms/aks.md
> Url -> URL

- docs/README.md
- docs/concepts/README.md
- docs/concepts/policy-crds/_index.md
- docs/concepts/secret-engine-crds/_index.md
- docs/concepts/secret-engine-crds/aws-secret-engine/_index.md
- docs/concepts/secret-engine-crds/aws-secret-engine/awsaccesskeyrequest.md
- docs/concepts/secret-engine-crds/aws-secret-engine/awsrole.md
- docs/concepts/secret-engine-crds/azure-secret-engine/_index.md
- docs/concepts/secret-engine-crds/azure-secret-engine/azureaccesskeyrequest.md
- docs/concepts/secret-engine-crds/azure-secret-engine/azurerole.md
- docs/concepts/secret-engine-crds/database-secret-engine/_index.md
- docs/concepts/secret-engine-crds/gcp-secret-engine/_index.md
- docs/concepts/secret-engine-crds/gcp-secret-engine/gcpaccesskeyrequest.md
- docs/concepts/secret-engine-crds/gcp-secret-engine/gcprole.md
- docs/guides/README.md
> Fix various formatting issues

- docs/concepts/what-is-kubevault.md
- docs/guides/monitoring/csi-driver/builtin.md
- docs/guides/monitoring/csi-driver/coreos.md
- docs/guides/monitoring/overview.md
- docs/guides/monitoring/vault-operator/builtin.md
- docs/guides/monitoring/vault-operator/coreos.md
- docs/guides/monitoring/vault-server/coreos.md
> Fix spelling and just use Prometheus operator

- docs/guides/monitoring/csi-driver/builtin.md
- docs/guides/monitoring/csi-driver/coreos.md
- docs/guides/monitoring/vault-operator/builtin.md
- docs/guides/monitoring/vault-operator/coreos.md
- docs/guides/platforms/multi-cluster-vault.md
- docs/setup/csi-driver/install.md
- docs/setup/csi-driver/uninstall.md
- docs/setup/operator/install.md
- docs/setup/operator/uninstall.md
- Make helm 3 recommended method
- Rewrite script to use helm 3
> Update installer instructions

- docs/setup/csi-driver/install.md
- docs/setup/operator/install.md
> Clean up reference to Stash

- docs/concepts/secret-engine-crds/_index.md
- docs/guides/monitoring/_index.md
- docs/guides/platforms/_index.md
- docs/guides/secret-engines/_index.md
- docs/guides/vault-server/_index.md
- docs/guides/vault-server/external-vault-sever.md
- docs/guides/vault-server/vault-server.md
> Fix formatting

- hack/scripts/open-pr.sh
> Add script to open pr

- docs/reference/cli/vault.md
- docs/reference/cli/vault_approve.md
- docs/reference/cli/vault_deny.md
- docs/reference/cli/vault_version.md
> Update docs for kubevault/cli@18ce00b2

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@dad30c6d

- .github/workflows/ci.yml
- docs/guides/secret-engines/mongodb/overview.md
- docs/guides/secret-engines/mysql/overview.md
> Use pre-built liche binary

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@7da8c693

- docs/CHANGELOG-v2020.07.09-beta.0.md
ProductLine: KubeVault
Release: v2020.07.09-beta.0
Release-tracker: https://github.com/kubevault/CHANGELOG/pull/3
> Prepare for release v2020.07.09-beta.0

- .github/workflows/ci.yml
> Skip checking GitHub urls

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@8ced55fa

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@c910de41

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@b8e9ae1f

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@9bc28ac1

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@293efbfd

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@56ab84c1

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@05dbb6d2

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@92a6d3d1

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@26c78e75

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@836ff706

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@c2fe16f6

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@dd754ac2

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@b7236c41

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@b3c8ee91

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@daa978d4

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@b9cfd37e

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@2256c39b

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@cf6451cb

- docs/reference/cli/vault_completion.md
> Update docs for kubevault/cli@cd5a4ddf

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@bce9789f

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@f46245ed

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@21be7a63

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@a8dc0965

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@1ee8c3cc

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@b770fbb4

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@0106b72e

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@9ed82704

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@ba023341

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@4fe93430

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@1dac2d38

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@b4fd21bc

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@32f30df5

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@6b713492

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@74bdab56

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@87792ad6

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@929db682

- docs/reference/cli/vault.md
- docs/reference/cli/vault_approve.md
- docs/reference/cli/vault_deny.md
- docs/reference/cli/vault_version.md
> Update docs for kubevault/cli@b2cb424d

- docs/reference/csi-driver/csi-vault.md
- docs/reference/csi-driver/csi-vault_run.md
- docs/reference/csi-driver/csi-vault_version.md
> Update docs for kubevault/csi-driver@de8f17ef

- docs/reference/unsealer/vault-unsealer.md
- docs/reference/unsealer/vault-unsealer_run.md
- docs/reference/unsealer/vault-unsealer_version.md
> Update docs for kubevault/unsealer@bdb094fa

- docs/reference/operator/vault-operator.md
- docs/reference/operator/vault-operator_run.md
- docs/reference/operator/vault-operator_version.md
> Update docs for kubevault/operator@e4d9e635

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@58aaa332

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@8b5a49bf

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@b644cefb

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@3c017799

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@93bc3231

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@5d2c7806

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@c47631ef

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@7a4231ed

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@b03e559d

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@78faf6f1

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@e91b82a2

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@f887799d

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@904f989b

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@66d27909

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@9bc0047a

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@2f044126

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@d2680695

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@1936a36d

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@70cfec70

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@dfcbbac4

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@1ed36be3

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@6d430966

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@17802cea

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@4020c9d9

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@e40c045d

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@132e7714

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@ef0eb40a

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@5863fd24

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@cc63443e

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@2cc2d037

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@a821055c

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@f4dc93a8

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@c501c8b0

- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@9f8e4b9b

- .github/workflows/ci.yml
- docs/concepts/vault-server-crds/storage/consul.md
- docs/reference/csi-driver/csi-vault_run.md
> Update docs for kubevault/csi-driver@93b97b48

- docs/guides/monitoring/vault-operator/builtin.md
- docs/guides/monitoring/vault-operator/coreos.md
- docs/guides/vault-server/vault-server.md
- docs/setup/operator/install.md
> Update labels to recommended k8s labels

- docs/setup/csi-driver/install.md
- docs/setup/operator/install.md
The links in the doc were broken.
Signed-off-by: Julien 'Lta' BALLET <contact@lta.io>
> Update link to charts source code in installer repo

- docs/examples/guides/secret-engines/kv/pod.yaml
- docs/examples/guides/secret-engines/kv/vaultPolicyBinding.yaml
- docs/guides/secret-engines/aws/csi-driver.md
- docs/guides/secret-engines/azure/csi-driver.md
- docs/guides/secret-engines/gcp/csi-driver.md
- docs/guides/secret-engines/kv/csi-driver.md
- docs/guides/secret-engines/mongodb/csi-driver.md
- docs/guides/secret-engines/mysql/csi-driver.md
- docs/guides/secret-engines/pki/csi-driver.md
- docs/guides/secret-engines/postgres/csi-driver.md
Hi, I updated the kv csi-driver page.
Please review it if you would like.
> Update kv csi driver page

- .github/workflows/preview-website.yml
> Enable website preview for pull requests

- .github/workflows/ci.yml
- docs/concepts/vault-server-crds/vaultserver.md
Signed-off-by: sakibalamin <sakibalamin@appscode.com>
> update vault docs

- cmd/vault-exporter/main.go
- cmd/vault-exporter/status.go
Signed-off-by: kamolhasan <kamol@appscode.com>
> Use certificate file paths instead of the certificates itself
